version: "3.8"
services:
    backend:
        build: ./Translator
        ports:
            - "5001:5001"
            - "5000:5000"
        restart: always
        expose:
            - 5001
        environment:
            ASPNETCORE_ENVIRONMENT: Development
    frontend:
        build: ./frontend
        restart: always
        ports:
            - "80:80"
        expose:
            - 80

